AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation template for setting up MySQL-Compatible Amazon Aurora RDS within the specified VPC, including subnet groups and instances.
  Follows 6 pillars of well architected framework along with their best practices.

Parameters:
  NamingPrefix:
    Type: String
    Default: term-end-app
    Description: Prefix for naming AWS resources

  DBUsername:
    Type: String
    Default: root
    Description: The database admin account username

  DBPassword:
    Type: String
    NoEcho: true
    Description: The database admin account password

Resources:
  # Database Subnet Group
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for DB
      SubnetIds:
        - !ImportValue core-infrastructure-PrivateDBSubnet1Id
        - !ImportValue core-infrastructure-PrivateDBSubnet2Id
      DBSubnetGroupName: !Sub '${NamingPrefix}-db-subnet-group'

  # DB Cluster
  DBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-mysql
      EngineMode: provisioned
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBSubnetGroupName: !Ref DBSubnetGroup
      VpcSecurityGroupIds:
        - !ImportValue core-infrastructure-PrivateDatabaseSGId
      BackupRetentionPeriod: 7
      PreferredBackupWindow: 07:00-09:00
      PreferredMaintenanceWindow: Mon:00:00-Mon:03:00
      EnableIAMDatabaseAuthentication: false
      Tags:
        - Key: Name
          Value: !Sub '${NamingPrefix}-db-cluster'

  # DB Instance 1
  DBInstance1:
    Type: AWS::RDS::DBInstance
    Properties:
      DBClusterIdentifier: !Ref DBCluster
      DBInstanceClass: db.t3.medium
      Engine: aurora-mysql
      Tags:
        - Key: Name
          Value: !Sub '${NamingPrefix}-db-instance-1'

  # DB Instance 2
  DBInstance2:
    Type: AWS::RDS::DBInstance
    Properties:
      DBClusterIdentifier: !Ref DBCluster
      DBInstanceClass: db.t3.medium
      Engine: aurora-mysql
      AvailabilityZone: us-east-1b
      Tags:
        - Key: Name
          Value: !Sub '${NamingPrefix}-db-instance-2'

  # Secrets Manager Secret
  DBSecret:
    Type: AWS::SecretsManager::Secret
    DependsOn: DBCluster
    Properties:
      Name: !Sub 'db-credentials'
      Description: 'Credentials for the Aurora DB Cluster'
      SecretString: !Join
        - ''
        - - '{ "username": "'
          - !Ref DBUsername
          - '", "password": "'
          - !Ref DBPassword
          - '", "host": "'
          - !GetAtt DBCluster.Endpoint.Address
          - '", "port": "3306", "dbname": "waiting_coder" }'
      Tags:
        - Key: Name
          Value: !Sub '${NamingPrefix}-db-secret'

Outputs:
  DBClusterId:
    Description: DB Cluster ID
    Value: !Ref DBCluster
    Export:
      Name: !Sub '${AWS::StackName}-DBClusterId'

  DBInstance1Id:
    Description: DB Instance 1 ID
    Value: !Ref DBInstance1
    Export:
      Name: !Sub '${AWS::StackName}-DBInstance1Id'

  DBInstance2Id:
    Description: DB Instance 2 ID
    Value: !Ref DBInstance2
    Export:
      Name: !Sub '${AWS::StackName}-DBInstance2Id'

  DBSecretArn:
    Description: ARN of the Secrets Manager Secret
    Value: !Ref DBSecret
    Export:
      Name: !Sub '${AWS::StackName}-DBSecretArn'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Database Configuration"
        Parameters:
          - DBUsername
          - DBPassword
    ParameterLabels:
      DBUsername:
        default: "Database Username"
      DBPassword:
        default: "Database Password"
